In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/atp_matches_2024.csv")

df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2024-0339,Brisbane,Hard,32,A,20240101,300,105777,2.0,NaN,...,58.0,44.0,16.0,11.0,8.0,9.0,14.0,2570.0,8.0,3660.0
1,2024-0339,Brisbane,Hard,32,A,20240101,299,208029,1.0,NaN,...,35.0,31.0,10.0,11.0,5.0,7.0,8.0,3660.0,39.0,1122.0
2,2024-0339,Brisbane,Hard,32,A,20240101,298,105777,2.0,NaN,...,39.0,24.0,14.0,10.0,5.0,7.0,14.0,2570.0,55.0,902.0
3,2024-0339,Brisbane,Hard,32,A,20240101,297,208029,1.0,NaN,...,51.0,31.0,16.0,10.0,3.0,5.0,8.0,3660.0,116.0,573.0
4,2024-0339,Brisbane,Hard,32,A,20240101,296,126128,NaN,NaN,...,37.0,27.0,16.0,10.0,5.0,8.0,39.0,1122.0,44.0,1021.0

In [4]:
df.shape
df.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry',
       'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age',
       'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand',
       'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round',
       'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon',
       'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt',
       'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points'],
      dtype='str')

In [5]:
df.isna().sum()

tourney_id               0
tourney_name             0
surface                  0
draw_size                0
tourney_level            0
tourney_date             0
match_num                0
winner_id                0
winner_seed           1782
winner_entry          2599
winner_name              0
winner_hand              0
winner_ht               19
winner_ioc               0
winner_age               1
loser_id                 0
loser_seed            2319
loser_entry           2358
loser_name               0
loser_hand               0
loser_ht                50
loser_ioc                0
loser_age                1
score                    0
best_of                  0
round                    0
minutes                238
w_ace                   60
w_df                    60
w_svpt                  60
w_1stIn                 60
w_1stWon                60
w_2ndWon                60
w_SvGms                 61
w_bpSaved               60
w_bpFaced               60
l_ace                   60
l_df                    60
l_svpt                  60
l_1stIn                 60
l_1stWon                60
l_2ndWon                60
l_SvGms                 61
l_bpSaved               60
l_bpFaced               60
winner_rank             17
winner_rank_points      17
loser_rank              40
loser_rank_points       40
dtype: int64

In [6]:
df.fillna({
    "winner_entry": "N",
    "loser_entry": "N"
}, inplace=True)
# Donde no aparecia nada en winner_entry y loser_entry, se reemplaza por N (Entraron normal, por ranking)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2024-0339,Brisbane,Hard,32,A,20240101,300,105777,2.0,N,...,58.0,44.0,16.0,11.0,8.0,9.0,14.0,2570.0,8.0,3660.0
1,2024-0339,Brisbane,Hard,32,A,20240101,299,208029,1.0,N,...,35.0,31.0,10.0,11.0,5.0,7.0,8.0,3660.0,39.0,1122.0
2,2024-0339,Brisbane,Hard,32,A,20240101,298,105777,2.0,N,...,39.0,24.0,14.0,10.0,5.0,7.0,14.0,2570.0,55.0,902.0
3,2024-0339,Brisbane,Hard,32,A,20240101,297,208029,1.0,N,...,51.0,31.0,16.0,10.0,3.0,5.0,8.0,3660.0,116.0,573.0
4,2024-0339,Brisbane,Hard,32,A,20240101,296,126128,NaN,N,...,37.0,27.0,16.0,10.0,5.0,8.0,39.0,1122.0,44.0,1021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3071,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4,D,20240203,5,212051,NaN,N,...,30.0,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0
3072,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,1,122533,NaN,N,...,41.0,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0
3073,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,2,144748,NaN,N,...,51.0,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN
3074,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,4,122533,NaN,N,...,51.0,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0
3075,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,5,202475,NaN,N,...,53.0,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN

In [7]:
df.fillna({
    "winner_entry": "Unseeded",
    "loser_entry": "Unseeded"
}, inplace=True)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2024-0339,Brisbane,Hard,32,A,20240101,300,105777,2.0,N,...,58.0,44.0,16.0,11.0,8.0,9.0,14.0,2570.0,8.0,3660.0
1,2024-0339,Brisbane,Hard,32,A,20240101,299,208029,1.0,N,...,35.0,31.0,10.0,11.0,5.0,7.0,8.0,3660.0,39.0,1122.0
2,2024-0339,Brisbane,Hard,32,A,20240101,298,105777,2.0,N,...,39.0,24.0,14.0,10.0,5.0,7.0,14.0,2570.0,55.0,902.0
3,2024-0339,Brisbane,Hard,32,A,20240101,297,208029,1.0,N,...,51.0,31.0,16.0,10.0,3.0,5.0,8.0,3660.0,116.0,573.0
4,2024-0339,Brisbane,Hard,32,A,20240101,296,126128,NaN,N,...,37.0,27.0,16.0,10.0,5.0,8.0,39.0,1122.0,44.0,1021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3071,2024-M-DC-2024-WG2-PO-URU-MDA-01,Davis Cup WG2 PO: URU vs MDA,Clay,4,D,20240203,5,212051,NaN,N,...,30.0,17.0,7.0,6.0,8.0,14.0,1109.0,8.0,740.0,34.0
3072,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,1,122533,NaN,N,...,41.0,25.0,6.0,9.0,1.0,4.0,554.0,67.0,748.0,32.0
3073,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,2,144748,NaN,N,...,51.0,25.0,7.0,11.0,5.0,12.0,416.0,109.0,NaN,NaN
3074,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,4,122533,NaN,N,...,51.0,32.0,17.0,14.0,5.0,9.0,554.0,67.0,416.0,109.0
3075,2024-M-DC-2024-WG2-PO-VIE-RSA-01,Davis Cup WG2 PO: VIE vs RSA,Hard,4,D,20240202,5,202475,NaN,N,...,53.0,25.0,8.0,8.0,9.0,14.0,748.0,32.0,NaN,NaN

In [8]:
df.isna().sum().sort_values(ascending=False).head(40)

loser_seed            2319
winner_seed           1782
minutes                238
w_SvGms                 61
l_SvGms                 61
l_df                    60
w_1stWon                60
w_bpFaced               60
w_bpSaved               60
w_2ndWon                60
w_1stIn                 60
w_df                    60
w_ace                   60
w_svpt                  60
l_svpt                  60
l_1stIn                 60
l_ace                   60
l_bpSaved               60
l_2ndWon                60
l_bpFaced               60
l_1stWon                60
loser_ht                50
loser_rank_points       40
loser_rank              40
winner_ht               19
winner_rank_points      17
winner_rank             17
loser_age                1
winner_age               1
tourney_id               0
draw_size                0
tourney_name             0
tourney_level            0
loser_id                 0
winner_ioc               0
winner_name              0
winner_hand              0
winner_entry             0
tourney_date             0
match_num                0
dtype: int64

In [9]:
estadisticas = [
    "w_ace", "w_df", "w_svpt",
    "l_ace", "l_df", "l_svpt"
]

df[df[estadisticas].isna().any(axis=1)][
    ["tourney_name", "winner_name", "loser_name", "score", "round"]
].head(20)

,tourney_name,winner_name,loser_name,score,round
12,Brisbane,Jordan Thompson,Ugo Humbert,W/O,R16
116,Auckland,Alejandro Tabilo,Cameron Norrie,W/O,QF
327,Dallas,Adrian Mannarino,Yoshihito Nishioka,W/O,R16
677,Indian Wells Masters,Holger Rune,Milos Raonic,W/O,R64
978,Barcelona,Alejandro Davidovich Fokina,Tomas Machac,W/O,R32
1061,Madrid Masters,Felix Auger Aliassime,Jannik Sinner,W/O,QF
1259,Geneva,Alexander Shevchenko,Emil Ruusuvuori,W/O,R16
1279,Lyon,Luciano Darderi,Arthur Rinderknech,W/O,QF
1286,Lyon,Giovanni Mpetshi Perricard,Yoshihito Nishioka,W/O,R16
1305,Roland Garros,Casper Ruud,Novak Djokovic,W/O,QF
1459,Stuttgart,Brandon Nakashima,Jan Lennard Struff,W/O,QF
1708,Wimbledon,Alex De Minaur,Lucas Pouille,W/O,R32
1722,Wimbledon,Novak Djokovic,Alex De Minaur,W/O,QF
2010,Paris Olympics,Jan Lennard Struff,Corentin Moutet,W/O,R32
2016,Paris Olympics,Alexander Zverev,Alexei Popyrin,7-5 6-3,R16
2023,Paris Olympics,Lorenzo Musetti,Alexander Zverev,7-5 7-5,QF
2043,Canada Masters,Sebastian Korda,Casper Ruud,W/O,R16
2092,Cincinnati Masters,Jannik Sinner,Jordan Thompson,W/O,R16
2150,Winston-Salem,Lorenzo Sonego,Juncheng Shang,W/O,R16
2352,Hangzhou,Rinky Hijikata,Fabian Marozsan,W/O,R16

In [10]:
df["tourney_level"].value_counts()

tourney_level
A    1519
M     695
G     508
D     260
O      64
F      30
Name: count, dtype: int64

NameError: name 'jugador' is not defined